sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/

install:
  - pip install flake8
  - pip install cookiecutter

script:
  - pwd
  - cookiecutter gh:praekelt/cookiecutter-python-package --no-input -o `pwd`
  - cd `pwd`/python_project && flake8
  - cd `pwd`/python_project && pip install -e .
  - cd `pwd`/python_project && py.test
