sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

install:
  - pip install coveralls
  - pip install wheel
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - py.test --cov={{cookiecutter.package_name}} --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{cookiecutter.pypi_username}}
  password:
    secure: "generate with travis encrypt"
  on:
    tags: true
    all_branches: true
